global using AutoMapper;
global using CandidateHubAPI.Dtos;
global using CandidateHubAPI.Models;
global using System.ComponentModel.DataAnnotations;
global using CandidateHubAPI.Validators;
global using CandidateHubAPI.Data;
global using Microsoft.EntityFrameworkCore;
global using CandidateHubAPI.Services;
global using Microsoft.AspNetCore.Mvc;